import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#13131b",
        "on-background": "#e4e1ed",
        surface: "#13131b",
        "on-surface": "#e4e1ed",
        "surface-dim": "#13131b",
        "surface-bright": "#393841",
        "surface-container-lowest": "#0d0d15",
        "surface-container-low": "#1b1b23",
        "surface-container": "#1f1f27",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "surface-variant": "#34343d",
        "on-surface-variant": "#c7c4d7",
        outline: "#908fa0",
        "outline-variant": "#464554",
        "inverse-surface": "#e4e1ed",
        "inverse-on-surface": "#303038",
        "inverse-primary": "#494bd6",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        secondary: "#89ceff",
        "on-secondary": "#00344d",
        "secondary-container": "#00a2e6",
        "on-secondary-container": "#00344e",
        "secondary-fixed": "#c9e6ff",
        "secondary-fixed-dim": "#89ceff",
        "on-secondary-fixed": "#001e2f",
        "on-secondary-fixed-variant": "#004c6e",
        tertiary: "#ffb783",
        "on-tertiary": "#4f2500",
        "tertiary-container": "#d97721",
        "on-tertiary-container": "#452000",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb783",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#703700",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c0c1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "0.5rem",
        sm: "1rem",
        gutter: "24px",
        md: "2rem",
        lg: "4rem",
        xl: "8rem",
        "max-width": "1280px",
      },
      fontFamily: {
        "headline-md": ["var(--font-jakarta)"],
        "display-lg": ["var(--font-jakarta)"],
        "display-lg-mobile": ["var(--font-jakarta)"],
        "body-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "label-mono": ["var(--font-geist)"],
      },
      fontSize: {
        "headline-md": [
          "32px",
          { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-mono": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": [
          "72px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
      },
      maxWidth: {
        "max-width": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
